system:
  thingName: {thing_name}
  privateKeyPath: "pkcs11:object={ggc.hsm.certandkey.label};type=private"
  rootCaPath: ~root/rootCA.pem
  certificateFilePath: "pkcs11:object={ggc.hsm.certandkey.label};type=cert"
services:
  main:
    lifecycle: {}
  aws.greengrass.Nucleus:
    version: {nucleus_version}
    configuration:
      awsRegion: {aws_region}
      envStage: {env_stage}
      iotCredEndpoint: {iot_cred_endpoint}
      iotDataEndpoint: {iot_data_endpoint}
      iotRoleAlias: {role_alias}
      greengrassDataPlanePort: {data_plane_port}
      deploymentPollingFrequencySeconds: 1
      networkProxy:
        proxy:
          url: {proxy_url}
      runWithDefault:
        posixUser: {posix_user}

  aws.greengrass.crypto.Pkcs11Provider:
    configuration:
      Name: {ggc_hsm_slotLabel}
      Library: {ggc_hsm_pkcs11ProviderPath}
      Slot: {ggc_hsm_slotId}
      UserPin: {ggc_hsm_slotUserPin}
