---
RecipeFormatVersion: 2020-01-25
ComponentName: com.aws.PingPong
ComponentVersion: '1.0.0'
ComponentDescription: My first AWS IoT Greengrass component.
ComponentPublisher: Amazon
ComponentConfiguration:
  DefaultConfiguration:
    accessControl:
      aws.greengrass.ipc.pubsub:
        "com.aws.PingPong:pubsub:1":
          policyDescription: Allows access to publish to say topics.
          operations:
            - "aws.greengrass#PublishToTopic"
            - "aws.greengrass#SubscribeToTopic"
          resources:
            - "say/pong"
            - "say/ping"
Manifests:
  - Artifacts:
      - URI: "file:target/aws-greengrass-testing-examples-component-1.0.0-SNAPSHOT.jar"
    Lifecycle:
      Run: |
        java -jar {artifacts:path}/aws-greengrass-testing-examples-component-1.0.0-SNAPSHOT.jar