name: Build then UAT
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'external_pr_*'
  pull_request:
    branches: '*'
env:
  AWS_REGION : "us-west-2"
  CODE_BUILD_PROJECT_LINUX: "OtfUatCodeBuildLinux"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Init Submodule
        run: git submodule update --init
      - name: Maven Preprocess
        run: mvn -U -ntp clean process-resources
      - name: Build with Maven
        run: mvn -U -ntp clean verify
      - name: Upload Failed Test Report
        uses: actions/upload-artifact@v1.0.0
        if: failure()
        with:
          name: Failed Test Report
          path: aws-greengrass-testing-features/aws-greengrass-testing-features-api/target/surefire-reports
      - name: Upload Failed Test Report for aws-greengrass-testing-launcher
          uses: actions/upload-artifact@v1.0.0
          if: failure()
          with:
            name: Failed Test Report
            path: aws-greengrass-testing-launcher/target/surefire-reports
      - name: Convert Jacoco unit test report to Cobertura
        run: python3 .github/scripts/cover2cover.py aws-greengrass-testing-features/aws-greengrass-testing-features-api/target/jacoco-report/jacoco.xml src/main/java > aws-greengrass-testing-features/aws-greengrass-testing-features-api/target/jacoco-report/cobertura.xml
      - name: Convert Jacoco unit test report to Cobertura for aws-greengrass-testing-launcher
          run: python3 .github/scripts/cover2cover.py aws-greengrass-testing-launcher/target/jacoco-report/jacoco.xml src/main/java > aws-greengrass-testing-launcher/target/jacoco-report/cobertura.xml
      - name: Upload Coverage
        uses: actions/upload-artifact@v1.0.0
        if: matrix.os == 'ubuntu-latest'
        with:
          name: Coverage Report
          path: aws-greengrass-testing-features/aws-greengrass-testing-features-api/target/jacoco-report
      - name: Upload Coverage for aws-greengrass-testing-launcher
          uses: actions/upload-artifact@v1.0.0
          if: matrix.os == 'ubuntu-latest'
          with:
            name: Coverage Report
            path: aws-greengrass-testing-launcher/target/jacoco-report
      - name: cobertura-report-unit-test
        uses: shaguptashaikh/cobertura-action@master
        continue-on-error: true
        with:
          # The GITHUB_TOKEN for this repo
          repo_token: ${{ github.token }}
          # Path to the cobertura file.
          path: aws-greengrass-testing-features/aws-greengrass-testing-features-api/target/jacoco-report/cobertura.xml
          # If files with 100% should be skipped from report.
          skip_covered: false
          # Minimum allowed coverage percentage as an integer.
          minimum_coverage: 60
          # Show line rate as specific column.
          show_line: true
          # Show branch rate as specific column.
          show_branch: true
          # Use class names instead of the filename
          show_class_names: true
          # Use a unique name for the report and comment
          report_name: Unit Tests Coverage Report
      - name: cobertura-report-unit-test for aws-greengrass-testing-launcher
          uses: shaguptashaikh/cobertura-action@master
          continue-on-error: true
          with:
            # The GITHUB_TOKEN for this repo
            repo_token: ${{ github.token }}
            # Path to the cobertura file.
            path: aws-greengrass-testing-launcher/target/jacoco-report/cobertura.xml
            # If files with 100% should be skipped from report.
            skip_covered: false
            # Minimum allowed coverage percentage as an integer.
            minimum_coverage: 60
            # Show line rate as specific column.
            show_line: true
            # Show branch rate as specific column.
            show_branch: true
            # Use class names instead of the filename
            show_class_names: true
            # Use a unique name for the report and comment
            report_name: Unit Tests Coverage Report for aws-greengrass-testing-launcher


  uat-linux:
    permissions:
      id-token: write
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::686385081908:role/aws-greengrass-testing-codebuild-uat-role-amazonlinux
          role-session-name: otfCI
          aws-region: ${{ env.AWS_REGION }}
      - name: Run UAT on linux
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: ${{ env.CODE_BUILD_PROJECT_LINUX }}
          buildspec-override: codebuild/uat_linux_buildspec.yaml


